### ISSUE TITLE
Caused by SSLError

### ISSUE THREAD

**Issue by makakin** [vavarachen/evtx2json#1]
$ python evtx2json.py --splunk --host localhost --port 8000 --token thisismytokenkeywithadminpermission process_files --files ~/Desktop/Logs/system.evtx

**Error: HTTPSConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /services/collector/event (Caused by SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:1076)')))**

**Comment by makakin** [comment]
python evtx2json.py process_files --files ~/Desktop/Logs/System.evtx

Using the above command, I can only get the output from the console only. How can I get the output file?

**Comment by aJesus37** [comment]
Not sure if the OP still needs this solution (outputing to files), but i've made a fork of this repo and added the -o/--output parameter to the script, now you can have an output. Or, if you give none, by default it will use the same path as the original file, but changing the end of file name to .json.
[Here's](https://github.com/aJesus37/evtx2json) the repo.

**Comment by vavarachen** [comment]
Apologies for a super-late response.

@makakin is it possible that you 'localhost' instance of Splunk HEC is using a self-signed certificate?   If you are using splunk_hec_handler module, disable ssl verification by passing 'ssl_verify'=False during handler init.
